### ISSUE TITLE
additional code attributes map

### ISSUE THREAD

**Issue by joeyjojo747** [radical-squared/aquatemp#10]
Can the additional codes be included. e.g T11?

If I add T11 to the config.yaml as an mapped attribute it breaks the integration.
T11 is not being returned

codes: 
- code: Power
  value: '1'
- code: Mode
  value: '1'
- code: Manual-mute
  value: '0'
- code: T01
  value: '10.5'
- code: T02
  value: '23.5'
- code: '2074'
  value: '0000000000000000'
- code: '2075'
  value: '0000000000000000'
- code: '2076'
  value: '0000000000000000'
- code: '2077'
  value: '0000000000000000'
- code: H03
  value: '0'
- code: Set_Temp
  value: '40.0'
- code: R08
  value: '8.0'
- code: R09
  value: '35.0'
- code: R10
  value: '15.0'
- code: R11
  value: '40.0'
- code: R01
  value: '28.1'
- code: R02
  value: '40.0'
- code: R03
  value: '28.0'
- code: T03
  value: '24.5'
- code: '1158'
  value: '1'
- code: '1159'
  value: '1'
- code: F17
  value: '0'
- code: H02
  value: '1'
- code: T04
  value: '8.0'
- code: T05
  value: '21.5'
- code: T06
  value: '64.0'
- code: T07
  value: '7.7'
- code: T12
  value: '585'
- code: T14
  value: '238'

**Comment by radical-squared** [comment]
If it's not returned then I'm afraid it's not supported by the system.

**Comment by radical-squared** [comment]
Try adding desired codes to line 305 of your local copy of the addon:

https://github.com/radical-squared/aquatemp/blob/b9c5f96fca681d3de8d5c957226bae072ea1fa0f/custom_components/aquatemp/climate.py#L305
