### ISSUE TITLE
What Device code to use?

### ISSUE THREAD

**Issue by robhellstrom** [radical-squared/aquatemp#12]
Is it possible to know what is the device code required to make this integration work? 

The two choices are the code on the pump and the code on the wifi device.

Can anyone tell me?

**Comment by migueldc73** [comment]
I am not sure what you mean with device code, but you first have to install the Aquatemp app on your IOS or Android phone. 
It will ask you to create and account (login & pwd), all of which you have probably already done.

Then, the first time you run the app it will ask for a code starting with "WF". This code is on a sticker on the outside of your heatpump, right next to the cable entry. 
I also had troubles finding this in the beginning.

After you installed the app and get it all running, you can then put the login & pwd into your configuration.yaml as described in this integration.

Once you have everything running, please let me know if you face the same problems as I do :  
1) each time I change a setting in the Aquatemp app, I get a "changed failed" error, even though the pump seems to execute the changes
2) the changes take 30sec to 1min to appear in both the phone app as this integration
3) it seems possible to turn off the pump from this HASS integration but not to turn it back on, see my other thread

I have been talking to the EU importer of this device, but the replies we get from the Chinese manufacturer of this WiFi device are complete rubbish. They either don't know what they are doing or not interested to give any decent support.

**Comment by jonathankretzmer** [comment]
Once you've connected the device to your Aqua Temp app, you can click on the hamburger menu and click on About. There is will provide you with your Device ID; mine is a long string of numbers.

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update (will require to read README and adjust configuration / reintegrate)

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please open another issue with details and logs

Thanks
