### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ChristianNiklasson** [radical-squared/aquatemp#13]
Will try to explain what has happened and not:

* Have existing Aquatemp account
* Tried to add the account in HA, ended up with my account being blocked and I couldn't log in from the phone app.
* Was in contact with the Suplier in Sweden, the couldn't even find my account.
* Set up new account (no heat pump added to account yet), new credentials added to HA.
* Works fine! (but no entity data for obvious reasons)
* Added the WiFi module/Heat pump to my new account in the phone app and.... get the following error:

Logger: custom_components.aquatemp.climate
Source: custom_components/aquatemp/climate.py:259 
Integration: aquatemp ([documentation](https://github.com/radical-squared/aquatemp)) 
First occurred: 17:31:52 (11 occurrences) 
Last logged: 17:41:53

Error logging in. Will keep on trying.

Config.YAML looks like this (hashed out now to prevent lockout of account again)

climate:
  - platform: aquatemp
    name: aquatemp
    username: !secret aquatemp_username
    password: !secret aquatemp_password
    min_temp: 20
    max_temp: 35
    temperature_unit: C
    unique_id: my_aquatemp
    expose_codes: true
    attribute_map:
      T05: ambient_temperature
      T03: outlet_temperature
      T02: inlet_temperature
      T01: suction_temperature

Am I supposed to change the unique_id to something? or is this just a friendly name?
If supposed to be changed then to what?

**Comment by radical-squared** [comment]
unique_id can be anything as far as it's unique. that's required by home assistant.  Make sure the attributes (e.g. T05) are indented under the attribute_map:

**Comment by ChristianNiklasson** [comment]
Indentation was not correct together with a typo in my !secrets file.
Thank you.
