### ISSUE TITLE
Update to readme for extended attributes

### ISSUE THREAD

**Issue by ianmcginley** [radical-squared/aquatemp#15]
Can we please get an update to the readme to show the added attributes available, particularly around power, and then how to use those to create power x amps = wattage and dashboard charts suggestions.

**Comment by galletn** [comment]
gpool is my pool / climate name, I take the value from the power and the amps and then calculate with it.

Hopes this helps (ps I'm not on the latest version yet of the code)

template:       
  - sensor:
      - name: Pool Heating Current
        unit_of_measurement: 'A'
        state: >- 
          {{ state_attr('climate.gpool', 'codes')[26].value }}
        state_class: measurement
        device_class: power
        
  - sensor:
      - name: Pool Heating Voltage
        unit_of_measurement: 'V'
        state: >- 
          {{ state_attr('climate.gpool', 'codes')[28].value }}
        state_class: measurement
        device_class: power
        
  - sensor:
      - name: Pool Heating Current Consumption
        unit_of_measurement: 'W'
        state: >- 
          {{ (state_attr('climate.gpool', 'codes')[28].value|float) * (state_attr('climate.gpool', 'codes')[26].value|float) }}
        state_class: measurement
        device_class: power

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update (will require to read README and adjust configuration / reintegrate)

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please open another issue with details and logs

Thanks
