### ISSUE TITLE
Exposing Attributes as Entities

### ISSUE THREAD

**Issue by t0b1as** [radical-squared/aquatemp#18]
I'd like to setup an automation based on inlet and outlet temperature. (Turning off circulation pump when inlet>outlet and pump on) How is it possible to expose the attributes as entities? Or even only do a greater than evaluation?

**Comment by t0b1as** [comment]
![Screenshot_2023-04-26-07-30-58-94_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/6332511/234478396-0a77ef84-8bd8-433b-bd9a-03fc7f144366.jpg)

Similar to what's shown here

**Comment by galletn** [comment]
Hi this is not an issue more a question for help.

you can create sensors using the templates in your config file.

example that I use on this integration:

`template: - sensor:
      - name: Pool Heating Current Consumption
        unit_of_measurement: 'W'
        state: >- 
          {{ (state_attr('climate.gpool', 'codes')[28].value|float) * (state_attr('climate.gpool', 'codes')[26].value|float) }}
        state_class: measurement
        device_class: power`

this creates an sensor of the power consumption of the heatpump based on the Amperage * Voltage. these are attributes that are number 28 and 26 in the values list. You just need to count them, might be prettier options too but it does the trick.

you conditions could be included too, but search on examples on templating for that. Easier option in my opinion is to use Node Red to do this kind of checks.

**Comment by t0b1as** [comment]
My point is a feature request to not having to frickle around with value conversion but to have them available as entities.

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please open another issue with details and logs

Thanks

**Comment by t0b1as** [comment]
Could you have a second look? Now it shows as an entity with properties, however to usefully evaluate each properties in standard automations, it's necesary to have each property as an individual entity. Would that be possible? That's also the same way tasmota devices show up for example.

**Comment by t0b1as** [comment]
(when comparing two properties the second needs to be a different entity, I don't know, could also be a bug in HA but that's how it is right now)

**Comment by elad-bar** [comment]
With v3.x you have use the various entities for each protocol code of the device exactly as described, in previous version (2.x) it was under one entity.

Not sure what do you mean by take a second look?
Can you please update the description of the issue now after integration refactored?

Thanks

**Comment by t0b1as** [comment]
Currently running 3.0.1. Just try replicating by making an automation with outlet<inlet temperature as trigger. It won't let you select the second value because both show up as the same entity.

**Comment by elad-bar** [comment]
Why do you keep comparing the climate entity with its attributes and note working with the relevant sensors?

Anyway, v3.0.9 is already available with many other fixes and improvements.
