### ISSUE TITLE
Force heatpump unit selection

### ISSUE THREAD

**Issue by Taz-assistant** [radical-squared/aquatemp#19]
I have two heatpump units registred on my aquatemp account (I have two pools).
How do I force the integration to choose a specific unit?
If I just install and run it works. But it controls the wrong unit.

**Comment by elad-bar** [comment]
for each device you can choose which temp. unit to use, default is `°C`

**Comment by elad-bar** [comment]
is that issue still relevant?

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please open another issue with details and logs

Thanks
