### ISSUE TITLE
Cannot Add Aqua Temp Integration

### ISSUE THREAD

**Issue by jendrzejczyk** [radical-squared/aquatemp#21]
Hello, I downloaded Aqua Temp via HACS, unfortunately I can not add Aqua Temp as an integration. I am supposed to edit the configuration.yaml, although the it should work via GUI. Is there a problem there? Thank you very much.

![grafik](https://github.com/radical-squared/aquatemp/assets/67321838/92d3464a-1e3d-49f7-8006-183b67ca6b01)

**Comment by marcinkowalczyk** [comment]
I can confirm same issue. HA 2023.5.4

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update
Integration name changed to `Aqua Temp`, pls follow the readme troubleshooting in case still not working for you

thanks

**Comment by sybux** [comment]
sorry but running 3.0.1 and impossible to connect : Invalid credentials

**Comment by elad-bar** [comment]
If you are getting the aquatemp and not 'Aqua Temp', it means you are not on the latest (v3.0.1),
Please delete the integration (after removing it), make sure nothing is configured for this integration over yaml,
Restart and install again from HACS, if not found, pls add as custom repo for integration and try again after additional restart of ha,
Pls let me know if it worked for you or not,
Thanks

**Comment by marcinkowalczyk** [comment]
Hi,

It's a bit tricky as integration was renamed. I had to remove files from custom-components restart HA and enter repo again as HACS was unable to handle rename case. Now it works flawless

**Comment by elad-bar** [comment]
Great, will add to readme steps to update

**Comment by elad-bar** [comment]
added, can you pls close the issue?

thanks
