### ISSUE TITLE
Disconnect repo from its original repo 

### ISSUE THREAD

**Issue by elad-bar** [radical-squared/aquatemp#36]
Repository represents a real custom component while original  is a script publishes MQTT messages to create MQTT components,
components created with that integration is much wider then available in the original one.

@radical-squared, can you please disconnect the repo in settings? (credits to initial work are availble in README).

**Comment by radical-squared** [comment]
True, just requested the repo be disconnected from the original script and become a new root.

**Comment by elad-bar** [comment]
thanks
