### ISSUE TITLE
HA loses connection with Aquatemp after approx 48hours

### ISSUE THREAD

**Issue by migueldc73** [radical-squared/aquatemp#42]
I wish all the issues were solved now, but I have this weird behaviour were I cannot turn the HAVC on/off after a certain time in use.
So everything runs fine and then after 24 to 48 hours, I get this error message :

__Failed to call service climate/set_temperature. Failed to set value of Set_Temp to {'param': [{'device_code': '98D863B43736', 'protocol_code': <ProtocolCode.TARGET_TEMPERATURE_HEAT: 'R02'>, 'value': 29.5}, {'device_code': '98D863B43736', 'protocol_code': <ProtocolCode.SET_TEMP: 'Set_Temp'>, 'value': 29.5}]}, Error: HTTP request to app/device/control.json, Status: 401, Message:__ 

The only solution is to reload the integration. Then it will work for another 24-48 hours...

Detailed logs attached
[Logs 11-June-2023.txt](https://github.com/radical-squared/aquatemp/files/11715254/Logs.11-June-2023.txt)

**Comment by greberg** [comment]
Yes, same for me and I also get this. It looks like the integration have problems to recover from error message from the API. Only way to get it up again is by restarting Home Assistant/reload the integration

Failed to fetch data, Error: HTTP request to app/device/getDataByCode.json, Status: 504, Message: Gateway Time-out
Failed to fetch data, Error: HTTP request to app/device/getDataByCode.json, Status: 502, Message: Bad Gateway
Failed to send passthrough instruction, Error: HTTP request to device/sendDevicePassthroughInstruction.json, Status: 502, Message: Bad Gateway
Failed to send passthrough instruction, Error: HTTP request to device/sendDevicePassthroughInstruction.json, Status: 401, Message:
Failed to fetch data, Error: HTTP request to app/device/getDataByCode.json, Status: 401, Message:

**Comment by Taz-assistant** [comment]
Exactly same here. Have been like this on all V 3.x.x.
V2.x.x did not have the same issue.
My temporary solution is an automation to restart integration if the
readings are stale for more than 30min.


Den mån 12 juni 2023 kl 09:27 skrev greberg ***@***.***>:

**Comment by radical-squared** [comment]
Disconnects did happen occasionally. V2.X would just reconnect in such case:
https://github.com/radical-squared/aquatemp/blob/a16ab6889d7d77f35f96b894c59bb416d8070093/custom_components/aquatemp/climate.py#LL306C1-L314C46

**Comment by elad-bar** [comment]
experienced it as well, fixed and tested yesterday [v3.0.10](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.10) should address it

error 401 - expired token - clean token and try login in next update (30 seconds)
error 502 - Bad Gateway - cannot reach destination, just log it
error 504 - Gateway Time-out - cannot reach destination, just log it

**Comment by elad-bar** [comment]
@radical-squared it is prefered to use the `response.raise_for_status()` validation,
in general the code in the link checks if status is 200, which is success, but it can be 300 which is also ok, in general any less than 400 is ok, which the function above is validating,
for errors that are not related to authentication (401) there is no need for relogin.

**Comment by radical-squared** [comment]
Supercool!

**Comment by elad-bar** [comment]
let's keep that issue open for 2 days and follow it up

**Comment by elad-bar** [comment]
did anyone experienced the same issue again or can we close that issue?

thanks

**Comment by migueldc73** [comment]
I don't have the issue anymore since the latest release. Thank you !

**Comment by elad-bar** [comment]
will close it, thanks for the update
