### ISSUE TITLE
Please update climate.py to show attributes

### ISSUE THREAD

**Issue by greberg** [radical-squared/aquatemp#5]
Please update device_state_attributes to extra_state_attributes to show all the attributes provided by aquatemp

Thanks

Best regards

**Comment by galletn** [comment]
@greberg please check out my pull request, it has a few more attributes and changed it to extra_state_attributes in order to use them after upgrade to 2022.4

let me know if additional changes are needed 👍 

https://github.com/galletn/aquatemp/tree/patch-1

**Comment by ludwich** [comment]
Love the new attributes. TY

**Comment by radical-squared** [comment]
@galletn PR merged. Many thanks for your contribution.
