### ISSUE TITLE
sensors have been lost

### ISSUE THREAD

**Issue by rodrigonogueras** [radical-squared/aquatemp#55]
Sensors that used to work have stopped appearing. Mainly:
sensor.pump_pool_ambient_temperature
sensor.pump_pool_inlet_water_temp
sensor.pump_pool_outlet_water_temp
![Imagen 002](https://github.com/radical-squared/aquatemp/assets/78388686/bde3c312-db93-4c13-b21a-afb8e255dbc2)
![Imagen 001](https://github.com/radical-squared/aquatemp/assets/78388686/e862f1cf-c09f-4e10-9923-b5a066a5ab24)

**Comment by greberg** [comment]
They have another name now with the updated version. Either you rename the sensor or rename the ui. Look in the integration component and you will see the new names.

**Comment by rodrigonogueras** [comment]
Sorry,

I saw the are new sensor with net numbers.

![image](https://github.com/radical-squared/aquatemp/assets/78388686/a42b9a26-e62f-44b0-966b-2091589fec53)

**Comment by elad-bar** [comment]
please check the new release [v3.0.14](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.14),
Added new sensor of `API Status`, will get disconnected state when the integration got "disconnection" error (401), it will also try to reauthenticate, so the expectation that you will just see that it got disconnected and connected again, but if it's not working, you can base automation upon state change,
pls let me know how it works for you

thanks

**Comment by MReuter2203** [comment]
With new Version I have the same issue.
I de-installed every thing and installed it again.
T2 and T3 are still unknown.

![image](https://github.com/radical-squared/aquatemp/assets/117604221/fe2d7cc9-0825-4594-8055-28201a23ac3d)

**Comment by elad-bar** [comment]
which version are you using?
can you pls provide logs?
can you pls also include diagnostic data?
I need that information to understand what went wrong

**Comment by MReuter2203** [comment]
I am using vers.3.0.14
I uploaded you the full log because I can not estimate what you need

[config_entry-aqua_temp-2e9bf2c925703cbc9e06fcae9d0f31ec.json.txt](https://github.com/radical-squared/aquatemp/files/11936880/config_entry-aqua_temp-2e9bf2c925703cbc9e06fcae9d0f31ec.json.txt)
[home-assistant_2023-07-03T12-49-46.320Z.log](https://github.com/radical-squared/aquatemp/files/11936916/home-assistant_2023-07-03T12-49-46.320Z.log)

**Comment by elad-bar** [comment]
can you please resend log but in debug level?
I do see a repeating error (below), but don't know what cause it.
```log
ERROR (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Failed to update (Attempt #3), Error: 'NoneType' object is not iterable, Line: 177
```

**Comment by elad-bar** [comment]
@greberg can you pls attach here logs in debug level so I will be able to understand the reason for that error and fix it?

thanks

**Comment by elad-bar** [comment]
Released new version [v3.0.15](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.15) with additional log to better understand the problem

**Comment by MReuter2203** [comment]
attached are the new logs with debug level
[home-assistant_2023-07-04T13-59-17.837Z.log](https://github.com/radical-squared/aquatemp/files/11950090/home-assistant_2023-07-04T13-59-17.837Z.log)
[config_entry-aqua_temp-2e9bf2c925703cbc9e06fcae9d0f31ec.json (2).txt](https://github.com/radical-squared/aquatemp/files/11950106/config_entry-aqua_temp-2e9bf2c925703cbc9e06fcae9d0f31ec.json.2.txt)

**Comment by elad-bar** [comment]
New release [v3.0.16](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.16), hopefully will solve that issue,
Seems that the getDataByCode endpoint is not returning error 401 when token expired but internal error code

pls let me know if it worked

thanks

**Comment by MReuter2203** [comment]
Did you public the new release because Hacs shows still the version 3.0.14. 
Thank you very much

**Comment by elad-bar** [comment]
I'm not sure what happened over the last 2 days, but releases are not being added to hacs, i shared the link to the release, set it as latest and yet it's not there

**Comment by elad-bar** [comment]
![Screenshot_20230704_204644_Home Assistant](https://github.com/radical-squared/aquatemp/assets/3207137/fbd882ff-0038-468e-a1f4-ba50a6e91fb0)

**Comment by MReuter2203** [comment]
Got latest version with "Download again" button.
I will give you feedback, asap

**Comment by MReuter2203** [comment]
I have the same issue like before.
T2 and T3 (Inlet / Outlet_water_temp are still unknown)
Attached my logs
[config_entry-aqua_temp-60f11a9b08a3d0bf0e7c5dfe926a2ee1.json.txt](https://github.com/radical-squared/aquatemp/files/11954276/config_entry-aqua_temp-60f11a9b08a3d0bf0e7c5dfe926a2ee1.json.txt)
[home-assistant_2023-07-05T05-42-20.509Z.log](https://github.com/radical-squared/aquatemp/files/11954277/home-assistant_2023-07-05T05-42-20.509Z.log)

**Comment by elad-bar** [comment]
I think I got it, it queries for T02 not T2, need to check what happend

**Comment by elad-bar** [comment]
And again... [v3.0.17](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.17), pls let me know if it works

thanks

**Comment by MReuter2203** [comment]
faster than the light. It works!
Great work.
Many many thanks, elad-bar

**Comment by elad-bar** [comment]
great! thanks for the update

**Comment by elad-bar** [comment]
@rodrigonogueras can we close the issue or is it still an issue?

thanks

**Comment by jonml** [comment]
Hi,
I’m still having the issue of the sensors not reporting any value after a day or so.  It looks like the API has disconnected.  I don’t use the Aqua Temp app to ensure it isn’t the stand alone app connecting and forcing HA integration to drop.

I updated to 3.0.17, as soon as it was available, and unfortunately still have this issue.  The new API sensor added a couple of versions back is still showing as ‘connected’ but unfortunately it doesn’t seem to be.

I have to reload the integration within the ‘settings - devices and services’.  The sensor gals then start appearing again in Home Assistant.

Thanks very much for your help with this

**Comment by elad-bar** [comment]
not sure I understand, what app did you use to connect the device?
if you are not using Aqua temp? what other app are you using? 
Can you pls share some logs of the disconnection? can't really understand what is the issue without it

thanks

**Comment by elad-bar** [comment]
in addition, I'm sure that with the latest versions the name of the sensors should be bit different. can you pls post also an update screen shot?

thanks

**Comment by rodrigonogueras** [comment]
> @rodrigonogueras can we close the issue or is it still an issue?
> 
> thanks

Sure, you can close the the issue.
