### ISSUE TITLE
climate entity naming glitch : _undefinedtype_singleton

### ISSUE THREAD

**Issue by migueldc73** [radical-squared/aquatemp#68]
After one of the last upgrades, I thought I lost my heatpump again, but then I noticed that the climate entity id had changed 👍 

It now has a strange suffix to the name : _undefinedtype_singleton

In my case : 

climate.warmtepomp_zwembad

became

climate.warmtepomp_zwembad_undefinedtype_singleton

I just renamed the entity, so no biggie, but it kind of indicates and underlying issue maybe ?

**Comment by davidjac** [comment]
Also getting exactly the same since last update with lots of duplicates marked unavailable entities. It appears to all work but there does seem to be a duplication problem. How to solve?
![image](https://github.com/radical-squared/aquatemp/assets/3065710/05d79d5f-c0f7-4e7a-922b-4ab5e9d6500a)
![image](https://github.com/radical-squared/aquatemp/assets/3065710/c61331e1-8ce1-4429-825c-332f1bcec0f4)

**Comment by elad-bar** [comment]
fixed in [v3.0.25](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.25), pls check and update

thanks

**Comment by sybux** [comment]
Came here for the same problem. Just updated to version 3.0.25 (I need to force the refresh and download in hacs).
Remove integration due to the invalid-token problem.
but at the end, all is fine, name is OK and got 161 sensors which is very very a lot :) for a so small device !!!

**Comment by elad-bar** [comment]
@sybux thanks for the update, regarding the sensors, if you have suggestion what to do with it, pls share :)

@migueldc73 did it solve it also for you?

thanks

**Comment by migueldc73** [comment]
@elad-bar 
Yes, this solves the problem for me.

I have another grip I recently discovered and put that in a new thread if you don't mind.

**Comment by elad-bar** [comment]
Thanks for the update, I don't see another thread, can you pls share a link to it?

Thanks

**Comment by migueldc73** [comment]
just added it : https://github.com/radical-squared/aquatemp/issues/70
