### ISSUE TITLE
Setpoint temperature becomes unavailable when the heatpump is turned off.

### ISSUE THREAD

**Issue by migueldc73** [radical-squared/aquatemp#70]
I recently moved from the standard climate card to a more advanced climate card and realized that, contrary to my Daikin airconditioning units, this integration does not keep the setpoint temperature active when the heatpump is turned off. 
![Heatpump Simple Thermostat bug 1](https://github.com/radical-squared/aquatemp/assets/107763234/181f6b33-fa24-47ae-acfb-9c4e2528a8cc)

This means that if someone would try to change the setpoint temperature while the heatpump is off, it will set it to ridiculously low values
![Heatpump Simple Thermostat bug 2](https://github.com/radical-squared/aquatemp/assets/107763234/25e92561-5aea-415f-b9df-0e6d069a4d5b)

This was not a problem previously because the default thermostat somehow turns setpoint selection off when the setpoint value is not available.

I could re-create a custom button car doing exactly that, but it would be nice if you have time to look into this such this heatpump behaves like the Daikin does: keeping the setpoint temperature value active while the heatpump is turned off.
![Heatpump Simple Thermostat bug 3 - Daikin](https://github.com/radical-squared/aquatemp/assets/107763234/c4f152a1-5a44-4a07-a7df-1301c1a04675)

If not possible, I'll start making a new custom climate card.

**Comment by elad-bar** [comment]
I understand the problem but it should be fixed on the card level not integration,
Reason - integration supports also heat/cool pump like mine, it also support auto mode, based on the mode the set point is being extracted from another parameter, therefore, when it's off, there is no way to predict the next mode and the parameter to extract the target temperature 
Hope it make sense

**Comment by migueldc73** [comment]
Totally makes sense, of course !
I will solve it on card level.

Thank you, I will closed this one.
