### ISSUE TITLE
Is there a way to remove unwanted daignostic sensors?

### ISSUE THREAD

**Issue by patfelst** [radical-squared/aquatemp#77]
Hi this is a great integration and it works great, I use it for my swimming pool heat pump.

But it exposes / creates 160 or so diagnostic sensors, and I only use about 5 of them. Is there any way to remove the majority of these, just leaving the ones I need, other than manually disabling each one, as I'm sure it puts a load on the HA host processor.

Thank you

**Comment by Know1** [comment]
It's a single call to the API so there's no extra load, apart from maybe a few more bytes of memory for more elements in the array.
As noted you can disable or change the property to hidden for each entity which will limit those shown, another method would be to not set an area for unwanted entities and then enable the global setting to not show entities without an area.

**Comment by patfelst** [comment]
ok thanks. Now with HA ability to bulk select entities and disable them in one go, this is a realistic solution.
