### ISSUE TITLE
Lost Climate HA integration

### ISSUE THREAD

**Issue by zappoo** [radical-squared/aquatemp#81]
Updated HACS AquaTemp integration from 3.0.29 to 3.0.31

HA integration continued to work but the entity named `[climate.xxx_pool_heater]` changed to Unavailable, meaning i could no longer have a nice thermostat display.

Downgraded to 3.0.29 and back to normal.

![image](https://github.com/radical-squared/aquatemp/assets/15315095/dc279e4f-67ea-4742-a20d-52d9d19503f8)

**Comment by Muzza** [comment]
Same here, although I'm struggling to get HA to let me download the earlier version.

EDIT: I updated to the latest HA Core (usually I wait a few weeks to let components catch up with any problems) and Aqua Temp seems to be working again. So it might just be that it is now incompatible with older versions of HA

**Comment by zappoo** [comment]
Confirmed.. Updating to the latest HA and Aquatemp and all ok.
