### ISSUE TITLE
Max temp on climate set to 28 C

### ISSUE THREAD

**Issue by PeterRemnemark** [radical-squared/aquatemp#86]
I'm using the 1.5.8 API integration to Aquatemp.

The climate control has a max setting to 28 C where the poolpump has a max temp as 40 C. Where is this controlled and set?

Have tried to locate in the code if there is any such settings but failed to find out. Is this 28 C set in the integration or is this coming from the interface with my pool pump?

Using the Aquatemp 3.0.32 version, and Home-Assistant as of 2024.5.5

Any tips or ideas much welcome since this integration is much better than the "./heatpump" version I used some while back.

**Comment by elad-bar** [comment]
you can download the diagnostic file from the intergation (device & services),
then you will be able to see all parameters.

In general, depends on the device you have there is mapping of which parameters to use, 
parameter files are available in the intergation directory of parameters - for instance, default configuration is being taken according to the following parameters:
```json
{
"cool": {
      "set": "0",
      "target": "R01",
      "minimum": null,
      "maximum": null
    },
    "heat": {
      "set": "1",
      "target": "R02",
      "minimum": "R08",
      "maximum": "R09"
    },
    "auto": {
      "set": "2",
      "target": "R03",
      "minimum": "R10",
      "maximum": "R11"
    }
  }

```

in addition, to compare it to the mobile app, you can find the names under the parameter settings in the app menu, code to enter the settings is `066`.

if you find it differently, maybe you have another device type and i need to add support for it,
please let me know how it works...

**Comment by PeterRemnemark** [comment]
thanks for the directions. Think I know why it ending up like it does in my case.

So my climate are set at heat.

In R09 it is set to 28.0C but the description for that parameter is Max.cool which does not make sense for heat mode.

If I would had auto on climate the R11 would be the 40.0C as I know would be max, and the description for that parameter is Max. Heat which make sense.

Is the R08 and R09 in your mapping or knowledge set to Min. Cool and Max. Cool? For my device it does not make sense to have climate set to heat and have the R08 and R09 as temp thresholds. Would rather be for climate mode "cool" and perhaps more auto mode, the Min. Cool and Max. Heat 

like this: 
`{
"cool": {
      "set": "0",
      "target": "R01",
      "minimum": "R08",
      "maximum": "R09"
    },
    "heat": {
      "set": "1",
      "target": "R02",
      "minimum": "R10",
      "maximum": "R11"
    },
    "auto": {
      "set": "2",
      "target": "R03",
      "minimum": "R08",
      "maximum": "R11"
    }
  }`

**Comment by elad-bar** [comment]
From the mobile app you can change that parameter (at your own risk), 
I would not do it before conaulting the right person,
I agree that 28 as maximum heat is not high enough, at my unit it is set to 35

**Comment by ChristianNiklasson** [comment]
Have the same issue as you, can max set it to 28°

**Comment by PeterRemnemark** [comment]
> From the mobile app you can change that parameter (at your own risk), I would not do it before conaulting the right person, I agree that 28 as maximum heat is not high enough, at my unit it is set to 35

Sure, and understand that option. However, not sure really if that is the issue here. Think the issue is that the default mapping in the integration (as setup) is not what the heat pump matches. 
As of the app, (sorry for the Swede lang, but you get the figures), I have it on heat (the solar) and when click on the change I have the range to change up to 40 as of the "Max Heat" parameter R11.

I tried to visualise that in the previous post but it was malformed.

![IMG_7356](https://github.com/radical-squared/aquatemp/assets/28634781/ef3f3bc4-1c99-4de6-bdc1-4a38bf621ea8)
![IMG_7357](https://github.com/radical-squared/aquatemp/assets/28634781/22565dd5-2ff4-4923-a812-6789caec0cce)

**Comment by elad-bar** [comment]
it should be as presented in the app, if you have set it, please download diagnostics file and share it, 
i will try to understand if it is still not working in alignment with what you have in the mobile app

**Comment by PeterRemnemark** [comment]
Thanks @elad-bar, appreciate your effort to look into this. See attached, let me know what I can do to assist you.

[config_entry-aqua_temp-8b249fb39a635e3f53aa42b33ddaeab3-2.json](https://github.com/user-attachments/files/15751303/config_entry-aqua_temp-8b249fb39a635e3f53aa42b33ddaeab3-2.json)

**Comment by elad-bar** [comment]
thanks for sharing that file, i found out that i mapped wrongly the HVAC modes and mixed up the parameters,
now the mapping is

| HVAC Mode | Set Point | Minimum | Maximum |
| --- | --- | --- | --- |
| Cool | R01 | R08 | R09 |
| Heat | R02 | R10 | R11 |
| Auto | R03 | R08 (Cool Min.) | R11 (Heat Max.) |


please share if it solved the issue for you

**Comment by PeterRemnemark** [comment]
> thanks for sharing that file, i found out that i mapped wrongly the HVAC modes and mixed up the parameters, now the mapping is
> 
> HVAC Mode	Set Point	Minimum	Maximum
> Cool	R01	R08	R09
> Heat	R02	R10	R11
> Auto	R03	R08 (Cool Min.)	R11 (Heat Max.)
> please share if it solved the issue for you

Yes it did! Thank you for the support 🥇

**Comment by elad-bar** [comment]
Great! Thanks for the update

**Comment by proasnet** [comment]
Dear @elad-bar ,
thank you for integration. I have the same issue now
Please, see attached log file.

[config_entry-aqua_temp-8b249fb39a635e3f53aa42b33ddaeab3-2.json](https://github.com/user-attachments/files/15926770/config_entry-aqua_temp-8b249fb39a635e3f53aa42b33ddaeab3-2.json)
.

**Comment by elad-bar** [comment]
@proasnet i was start to worry that i fixed for one and messed it for others :)
pls upgrade to latest (v3.0.36), seems that you are running v3.0.32 installed (issue above fixed in v3.0.35)

thanks

**Comment by proasnet** [comment]
Dear @elad-bar , thank you for your reply.
I look in HACS to see what version is downloaded. I have 3.0.36 there. I was adding the integration today. Do you have any idea please?

**Comment by elad-bar** [comment]
according to the file you have shared:
```json
"aqua_temp": {
      "documentation": "https://github.com/radical-squared/aquatemp",
      "version": "3.0.34",
      "requirements": []
    },
```

can you check also within devices & service -> aqua temp integration what is the version below the logo?

thanks

**Comment by proasnet** [comment]
![obrazek](https://github.com/radical-squared/aquatemp/assets/76579362/74158804-c580-4d29-adeb-8fe4bcf240d0)

**Comment by proasnet** [comment]
Now is set temperature on device to 30°C, and actual is fine.
Max limit on device is 40°C.

![obrazek](https://github.com/radical-squared/aquatemp/assets/76579362/d479d7e8-910c-4ffb-b0c4-693fbfdf1600)
